name : CI/CD

on:
  push:
      branches:
        - master

jobs:
  ci-cd:
    name : CI/CD
    runs-on: ubuntu-latest

    steps :
      - name: "init"
        uses: actions/checkout@v2

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.7

      - name: "Deploy"
        run: |
          gem install dpl
          dpl --provider=heroku --app=${{ secrets.HEROKU_APP }} --api-key=${{ secrets.HEROKU_API_KEY }} --skip_cleanup=true